
# services:
#   db:
#     image: postgres:15
#     platform: linux/amd64
#     container_name: guiaorla_db
#     restart: always
#     environment:
#       POSTGRES_DB: guiaorla
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     ports:
#       - "5433:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d guiaorla"]
#       interval: 5s
#       timeout: 5s
#       retries: 10

#   backend:
#     build: ./backend/GuiaOrlaPE.API
#     platform: linux/amd64
#     container_name: guiaorla_backend
#     depends_on:
#       db:
#         condition: service_healthy
#     ports:
#       - "5000:8080"
#       - "5148:8080"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=guiaorla;Username=postgres;Password=${POSTGRES_PASSWORD}
#       - Jwt__Key=${JWT_KEY}
#     restart: on-failure

#   frontend:
#     build:
#       context: ./frontend/guiaorla-frontend
#       args:
#         NEXT_PUBLIC_API_URL: http://localhost:5000
#     container_name: guiaorla_frontend
#     depends_on:
#       - backend
#     ports:
#       - "3000:3000"
#     environment:
#       - API_URL_INTERNAL=http://backend:8080

# volumes:
#   db_data:

services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: guiaorla_db
    restart: always
    environment:
      POSTGRES_DB: guiaorla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d guiaorla"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend/GuiaOrlaPE.API
    platform: linux/amd64
    container_name: guiaorla_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"
      - "5148:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=guiaorla;Username=postgres;Password=${POSTGRES_PASSWORD}
      - Jwt__Key=${JWT_KEY}
    volumes:
      # Adicione esta linha abaixo para conectar sua pasta local ao container
      - ./backend/GuiaOrlaPE.API/wwwroot/uploads:/app/wwwroot/uploads
    restart: on-failure

  frontend:
    build:
      context: ./frontend/guiaorla-frontend
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: guiaorla_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - API_URL_INTERNAL=http://backend:8080

volumes:
  db_data: