services:
  db:
    image: postgres:15
    platform: linux/amd64
    container_name: guiaorla_db
    restart: always
    environment:
      POSTGRES_DB: guiaorla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend/GuiaOrlaPE.API
    container_name: guiaorla_backend
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=guiaorla;Username=postgres;Password=postgres


  frontend:
    build: ./frontend/guiaorla-frontend
    container_name: guiaorla_frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000

volumes:
  db_data: