version: '3.8'

services:
  db:
    image: postgres:15
    container_name: guiaorla_db
    restart: always
    environment:
      POSTGRES_DB: guiaorla
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend/GuiaOrlaPE.API
    container_name: guiaorla_backend
    depends_on:
      - db
    ports:
      - "5000:80"

  frontend:
    build: ./frontend/guiaorla-frontend
    container_name: guiaorla_frontend
    ports:
      - "3000:3000"